### ISSUE TITLE
Allow direct `go generate` usage (no CLI)

### ISSUE THREAD

**Issue by bojanz** [lu4p/binclude#10]
Here's an official feature request, repeating what I said on Reddit:
```
 I would appreciate being able to run the generator from my own _gen.go file, instead of having to rely on the binclude binary (which requires ensuring I have installed it up front, and I guess maintaining a tools.go file for that purpose).
```

This would require moving the relevant code from cmd/bininclude to the parent package, so that it can be called both by random callers and the CLI.

Right now only vfsgen in the entire ecosystem supports this, so it would be a big plus for this package to cover it.

**Comment by lu4p** [comment]
I don't think the parent package is the right package because it would add some dependencies like `go/ast`. I can add a new package like binclude-gen.

**Comment by lu4p** [comment]
@bojanz Added support for generating code from your own generator file `bincludegen.Generate(binclude.None)`

**Comment by bojanz** [comment]
Thanks lu4p, you rock!
