### ISSUE TITLE
Remove support for Brotli

### ISSUE THREAD

**Issue by bojanz** [lu4p/binclude#11]
This is something I've never done before, an anti-feature request :)

You recently added optional GZip and Brotli support. They cover the same use case, with Brotli offering slightly better filesizes. Since Brotli isn't supported by Go by default, you had to pull in the github.com/andybalholm/brotli package. This package is anything but small:
```
❯ gocloc brotli
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Go                              61           2451           1941         252967
Plain Text                       1            815              0           8471
Markdown                         1              1              0              4
-------------------------------------------------------------------------------
TOTAL                           63           3267           1941         261442
-------------------------------------------------------------------------------
```

Is an optional feature worth adding 260k lines of code? I'd argue no. Furthermore, aletheia-icu/broccoli already covers the "embed files with brotli compression" use case, for those interested in it (and not afraid of the large dependency).

**Comment by lu4p** [comment]
How much does this add to the final binary?

**Comment by lu4p** [comment]
@audiolion What are your thoughts on this?

**Comment by audiolion** [comment]
I guess forcing everyone who uses this package to include such a large dependency seems bad. What about letting the user pass their own Reader/Writer, and that way they can download `github.com/andybalholm/brotli` and pass in brotli for compression, or any other one they please?

**Comment by lu4p** [comment]
It's not that simple because the user only controls compression via flags. 

But compression for the sake of smaller binaries is a non goal of this project (use upx) and brotli isn't well supported enough on the web yet that it would make sense to only serve brotli compressed content. So I remove brotli compression for the sake of smaller binaries.

**Comment by bojanz** [comment]
Thanks!

FWIW, the Brotli package added about 5.5mb (5654kb) to my binary size.
