### ISSUE TITLE
os/exec wrapper caching

### ISSUE THREAD

**Issue by audiolion** [lu4p/binclude#13]
The os/exec wrapper is a really useful feature. As I understand the feature it copies the embedded byte slice to a temporary file in the os.CacheUserDir(), executes it, and then removes it. This is a sane default, but if the embedded binary is large (in my case, 80mb), this will take a long time to copy and use each time. I wonder if there should be an option to disable the removal, and a potential warning logged when calling os/exec on a large binary, or if this is a feature that people should just implement on their own (extracting the embedded file to wherever and calling os/exec on it). I can really see this -not- being a feature that is added, but if it is not, I wonder if there should be some documentation or warning that this could be expensive for large binaries because it copies them each time.

**Comment by lu4p** [comment]
> The os/exec wrapper is a really useful feature. As I understand the feature it copies the embedded byte slice to a temporary file in the os.CacheUserDir(), executes it, and then removes it.

Yes thats exacly what it does, you are right I should add e caching function.

This is what I have in mind:
https://github.com/lu4p/binclude/blob/master/binexec/binexec.go:
``` go
// Cmd same as Cmd in the os/exec package
type Cmd struct {
	OsCmd *exec.Cmd
        Cache bool // add this field
}
```
Usage:
``` go
cmd, _ := binexec.Command(BinFS, "command", "arg")
cmd.Cache = true // if this is set remove won't be called a the file
```

**Comment by audiolion** [comment]
looks good to me, I don't want to make life harder but do you think there should be control over where it is placed as well? If you don't want it in the user cache dir?

**Comment by lu4p** [comment]
I the user shouldn't control where the file is placed, if the user wants to have control he can always copy the file to the on its own using `BinFs.CopyFile()` and use the `os/exec` package.

**Comment by lu4p** [comment]
How do I know if the file is already cached, I first thought of hashes but reading the whole file cached in memory and then building hashes is expensive.

**Comment by audiolion** [comment]
You could store when the file was last modified when you write it, if the timestamp hasn't changed the file hasn't changed. Otherwise doing checksums is going to be expensive. My only advice there is to compute checksums every 100mb or so and save them, then as you are checking the checksum you can bail out early if it doesn't match to save some work. But honestly that seems like a ton of work, the timestamp of the file seems far simpler and good enough.

**Comment by lu4p** [comment]
I also thought of that problem being, that windows has no support for file.Modtime() see the implementation [here](https://github.com/golang/go/blob/83b181c68bf332ac7948f145f33d128377a09c42/src/os/types_windows.go#L136)

**Comment by audiolion** [comment]
It looks like it returns the last write time, what is the issue with that?

**Comment by lu4p** [comment]
I can add the `ModTime.Nanosecond()` to the files modtime which is currently `time.Unix(second, 0)` as this also works on windows. And then use the Nanoseconds.

**Comment by lu4p** [comment]
> It looks like it returns the last write time, what is the issue with that?

It only returns the nanosecond offset not the seconds since unix epoch.

**Comment by lu4p** [comment]
Done.
