### ISSUE TITLE
Binclude generated code doesn't always match go fmt

### ISSUE THREAD

**Issue by audiolion** [lu4p/binclude#14]
When I run binclude, some of the time the generated code does not match go fmt so I have to run go fmt against the file after generation. Specifically there is extra space between the variable declarations and the `=` sign that needs to be removed:

## Current binclude generated output
![image](https://user-images.githubusercontent.com/2430381/87674329-dc3ddf00-c743-11ea-8736-847076163bdf.png)

## After I run go fmt
![image](https://user-images.githubusercontent.com/2430381/87674492-127b5e80-c744-11ea-915a-c2d8dd8888e9.png)

**Comment by lu4p** [comment]
Can you label the pictures to indicate which is which?

**Comment by audiolion** [comment]
added labels, I can try to create a reproducible case later

**Comment by lu4p** [comment]
@audiolion Fixed it.

**Comment by audiolion** [comment]
awesome! thanks
