### ISSUE TITLE
Does this works for binary files

### ISSUE THREAD

**Issue by davinash** [lu4p/binclude#7]
I am trying for binary files, but I am always getting error
```

binclude.Include("./out/MyExe")

err := example.BinFS.CopyFile("MyExe", filepath.Join(destination, "MyExe"))
		if err != nil {
			fmt.Printf("1 :: Failed to copy file to destination, error = %v\n", err)
			//os.Exit(1)
		}
		err = example.BinFS.CopyFile("out/MyExe, filepath.Join(destination, "MyExe"))
		if err != nil {
			fmt.Printf("2 :: Failed to copy file to destination, error = %v\n", err)
			//os.Exit(1)
		}
		err = example.BinFS.CopyFile("./out/MyExe", filepath.Join(destination, "MyExe"))
		if err != nil {
			fmt.Printf("3 ::Failed to copy file to destination, error = %v\n", err)
			//os.Exit(1)
		}
```

**Comment by davinash** [comment]
Error is :  File does not exist in binclude map

**Comment by davinash** [comment]
Strange with 
```
binclude.Debug = true
err = example.BinFS.CopyFile("out/MyExe, filepath.Join(destination, "MyExe"))
		if err != nil {
			fmt.Printf("2 :: Failed to copy file to destination, error = %v\n", err)
			//os.Exit(1)
		}
```
It looks like working

**Comment by lu4p** [comment]
> I am trying for binary files, but I am always getting error
> 
> ```
> 
> binclude.Include("./out/MyExe")
> 
> err := example.BinFS.CopyFile("MyExe", filepath.Join(destination, "MyExe"))
> 		if err != nil {
> 			fmt.Printf("1 :: Failed to copy file to destination, error = %v\n", err)
> 			//os.Exit(1)
> 		}
> 		err = example.BinFS.CopyFile("out/MyExe, filepath.Join(destination, "MyExe"))
> 		if err != nil {
> 			fmt.Printf("2 :: Failed to copy file to destination, error = %v\n", err)
> 			//os.Exit(1)
> 		}
> 		err = example.BinFS.CopyFile("./out/MyExe", filepath.Join(destination, "MyExe"))
> 		if err != nil {
> 			fmt.Printf("3 ::Failed to copy file to destination, error = %v\n", err)
> 			//os.Exit(1)
> 		}
> ```

Did you run binclude again to regenerate the binclude.go file?

**Comment by davinash** [comment]
I did , I am running each time
go generate
go build

**Comment by lu4p** [comment]
You need to use `BinFS.CopyFile("` instead of `example.BinFS.CopyFile("`

**Comment by davinash** [comment]
Thanks for your quick comment, but I did not understand last comment, I was using code from the https://github.com/lu4p/binclude/blob/master/binclude_test.go

**Comment by lu4p** [comment]
The reason this doesn't works is because you use the filesystem from github.com/lu4p/example so you need to use the generated Filesystem which is part of the same package. 

Like this:

```go
binclude.Include("./out/MyExe")

err := BinFS.CopyFile("MyExe", filepath.Join(destination, "MyExe"))
		if err != nil {
			fmt.Printf("1 :: Failed to copy file to destination, error = %v\n", err)
			//os.Exit(1)
		}
		err = BinFS.CopyFile("out/MyExe, filepath.Join(destination, "MyExe"))
		if err != nil {
			fmt.Printf("2 :: Failed to copy file to destination, error = %v\n", err)
			//os.Exit(1)
		}
		err = BinFS.CopyFile("./out/MyExe", filepath.Join(destination, "MyExe"))
		if err != nil {
			fmt.Printf("3 ::Failed to copy file to destination, error = %v\n", err)
			//os.Exit(1)
		}

```

**Comment by davinash** [comment]
Thanks It is working now.

**Comment by lu4p** [comment]
You can also use the binexec package to run an executable directly from the binary
