### ISSUE TITLE
Include expects a constant string literal

### ISSUE THREAD

**Issue by davinash** [lu4p/binclude#8]
I may be using the API incorrectly. binclude.Include always expects string literal.
binclude.Include(fmt.Sprintf("%s", "./out/myexe"))
Does not work and give error 

[binclude] 2020/06/26 06:09:47 argument is not string literal

Is there a way to avoid this, I am looking for reading the file name from say input json

**Comment by lu4p** [comment]
This is not possible, because binclude runs before any of the code runs/ you cannot include files at runtime.

What exactly are you trying to achieve? I could add support for let's say `binclude.IncludeFromFile("files.text") which reads a text file which contains the paths to include.

**Comment by davinash** [comment]
Yes, That would really help. Thanks

**Comment by lu4p** [comment]
@davinash Added support for `binclude.IncludeFromFile("includefiles.text")`
