### ISSUE TITLE
Evaluate binclude.Include based on build tags

### ISSUE THREAD

**Issue by audiolion** [lu4p/binclude#9]
Is it possible to use binclude to selectively include files based on build tags? For instance, if I am building for windows amd64, include X file?

```go
//+build windows

import "github.com/lu4p/binclude"

binclude.Include("/windows-thing.dll")
```

**Comment by lu4p** [comment]
Good idea currently it doesn't work, will add support.

**Comment by lu4p** [comment]
@audiolion I now added support for implicit filename based build tags like `file_linux.go`, `file_windows.go`,  `file_darwin_arm.go`

### From the build documentation: 

If a file's name, after stripping the extension and a possible _test suffix, matches any of the following patterns:

*_GOOS
*_GOARCH
*_GOOS_GOARCH

(example: source_windows_amd64.go) where GOOS and GOARCH represent any known operating system and architecture values respectively, then the file is considered to have an implicit build constraint requiring those terms (in addition to any explicit constraints in the file).

**Comment by audiolion** [comment]
Thanks for the fast turnaround. I will try it out next week at work. Would you like a PR to document the feature? I don't think other embeds like go.rice, packr/pkger, have this feature.

**Comment by lu4p** [comment]
PRs which improve the docs are welcome :+1:

**Comment by lu4p** [comment]
Actually this isn't finished yet. I could generate different files like binclude_windows.go binclude_linux.go binclude_darwin.go, this would allow embeddding different files for each os and avoid the need to regenerate the file when the platform changes.

**Comment by lu4p** [comment]
Done
